CREATE DATABASE db_users;
ALTER DATABASE db_users CHARACTER SET = utf8mb3;

USE db_users;

CREATE TABLE Usuarios(
	pkUser INT PRIMARY KEY AUTO_INCREMENT,
    user_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    pwdHash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Endereco(
    pkEndereco INT PRIMARY KEY AUTO_INCREMENT,
    rua VARCHAR(255) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    cidade VARCHAR(255) NOT NULL,
    numero INT NOT NULL,
    cep VARCHAR(8) NOT NULL,
    fkUser INT NOT NULL UNIQUE
);

ALTER TABLE Endereco 
ADD CONSTRAINT fk_Usuarios_Endereco FOREIGN KEY(fkUser) REFERENCES Usuarios(pkUser);

CREATE TABLE Telefone(
    pkTelefone INT PRIMARY KEY AUTO_INCREMENT,
    numero VARCHAR(255) NOT NULL,
    fkUser INT NOT NULL UNIQUE
);

ALTER TABLE Telefone
ADD CONSTRAINT fk_Usuarios_Telefone FOREIGN KEY(fkUser) REFERENCES Usuarios(pkUser);